### ISSUE TITLE
Can we change the month/year selector button

### ISSUE THREAD

**Issue by jackxyf7689** [kekeh/mydatepicker#130]
Hi, the datepicker is wonderful, when I am using it, I wonder whether I can change the month/year selector button to this one "prev btn MONTH YEAR next btn"?

Thanks.

**Comment by mailsunil123** [comment]
Hi kekeh,

I was using your calendar control and it was working fine. But when I reinstalled my npm packages today, I'm getting below error

(index):131 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost/account/traceur
	Error: XHR error (404 Not Found) loading http://localhost/account/traceur
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost/account/lib/zone.min.js:1:730)
	    at e.invokeTask (http://localhost/account/lib/zone.min.js:1:15126)
	    at n.runTask (http://localhost/account/lib/zone.min.js:1:12486)
	    at XMLHttpRequest.invoke (http://localhost/account/lib/zone.min.js:1:16239)
	Error loading http://localhost/account/traceur
	Unable to load transpiler to transpile http://localhost/account/node_modules/mydatepicker/dist/my-date-picker.module.js
	Error loading http://localhost/account/node_modules/mydatepicker/dist/my-date-picker.module.js as "mydatepicker/dist/my-date-picker.module" from http://localhost/account/app/app.module.js
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost/account/lib/zone.min.js:1:730)
	    at e.invokeTask (http://localhost/account/lib/zone.min.js:1:15126)
	    at n.runTask (http://localhost/account/lib/zone.min.js:1:12486)
	    at XMLHttpRequest.invoke (http://localhost/account/lib/zone.min.js:1:16239)
	Error loading http://localhost/account/traceur
	Unable to load transpiler to transpile http://localhost/account/node_modules/mydatepicker/dist/my-date-picker.module.js
	Error loading http://localhost/account/node_modules/mydatepicker/dist/my-date-picker.module.js as "mydatepicker/dist/my-date-picker.module" from http://localhost/account/app/app.module.js

Do you know why it is happening.

**Comment by kekeh** [comment]
Update the latest version and follow instructions from here: https://github.com/kekeh/mydatepicker/blob/master/README.md

**Comment by mailsunil123** [comment]
Hi kekeh, 

Thanks for the response.
I afraid I cannot upgrade to latest version at this moment as it involves lot of process for us.
When I just used  version 1.1.5 then it worked. 
I'm using angular 2.1.1 and the latest version of datepicker required a later version of angular. 
Also, looks like typescsript also needs to be upgrade dto 2.0 or above.

**Comment by kekeh** [comment]
I think you can use the latest version **1.6.1**. Only requirements, if you are using systemjs, is that you import the mydatepicker this way in your app module:

```ts
import { MyDatePickerModule } from 'mydatepicker';
```

and define the mydatepcker this way in your systemjs config:

```js
    (function (global) {
        System.config({
            paths: {
                'npm:': 'node_modules/'
            },
            map: {
                // Other components are here...

                'mydatepicker': 'npm:mydatepicker/bundles/mydatepicker.umd.js'
            },
            packages: {
            }
        });
    })(this);
```

These things have changed recently.
