### ISSUE TITLE
ERROR in ./~/MyDatePicker/src/my-date-picker/my-date-picker.component.scss

### ISSUE THREAD

**Issue by mstang** [kekeh/mydatepicker#24]
I think I have all the requirements, but I am getting this:

Module parse failed:     /home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/MyDatePicker/src/my-date-picker/my-date-picker.component.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.parseExprAtom (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:1753:23)
    at Parser.pp.parseTopLevel (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/mstang/Downloads/projects/Java/leadershipw/src/main/angular2/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./~/MyDatePicker/src/my-date-picker/my-date-picker.component.ts 13:13-55

**Comment by kekeh** [comment]
Are you able to run sample app? Take pull first and then:

1. Open a terminal and type "npm start"
2. http://localhost:5000

**Comment by mstang** [comment]
Thanks, I will try that.
My initial issue was with webpack and not installing the loader.  After I
had the loader configured, I ran into other issues.
So, I will try your recommendations first and see if I can get it to work
locally.

Thanks!

Mark

**Comment by allauthors** [comment]
@mstang I'm having the same original issue you reported... Can you share how you configured the loader to get past that?

**Comment by kekeh** [comment]
I defined loaders this way to the **webpack.config.js** file:
`
  module: {
    loaders: [
            {test: /\.ts$/, exclude: [/\.spec\.ts$/, /node_modules/], loader: 'ts'},
            {test: /\.html$/, loader: 'raw'},
            {test: /\.scss$/, include: [path.resolve(__dirname, 'src')], loader: 'raw!postcss-loader!sass'}

    ]
`

and it resolve this issue.

**Comment by mstang** [comment]
I never got past the error, dropped it and went on to other things.
However, it looks like he has a solution, let me know if it works for you.

regards,

Mark
