### ISSUE TITLE
Month selection only

### ISSUE THREAD

**Issue by Chadley08** [kekeh/mydatepicker#333]
This would be a new feature for the control. It would have a mode which allows the user to select the month in a year only. (Basically just displaying and using the month view only).

**Comment by michalczukm** [comment]
I would also appreciate this feature. I can handle it in about a week or two.
@kekeh any objectives or any guidelines?

**Comment by edgexie** [comment]
hi, I care about this function. when will it join?

**Comment by src-mgra** [comment]
@michalczukm: Do you have as solution for a month-selection returning month and year ? I am looking for this feature. Because mydatepicker works very well with Ionic.

**Comment by michalczukm** [comment]
Hi,
Sorry guys, I've forgot about an issue. Feel free to take it, I'm not sure if I'll find time for it in upcoming week.

**Comment by edgexie** [comment]
@src-mgra Do you have any message of this function that you need? I need month-selection and year-selection too.

**Comment by src-mgra** [comment]
Hi @edgexie I need the month/year-selection too and actually I am not planed to develope one. I try to extract only month an year by a selected day with a special option. So currently functionality works for me.
The picker works fine with ionic. Let me know if you have any news for month-pickers.

**Comment by michalczukm** [comment]
I've failed with installing the dependencies, @kekeh what setup do you have?
I'm constantly getting timeouts during installation (no proxy, tested on multiple machines).

```
node: v8.1.2
npm: 5.4.1
```

```
15474 silly extract beeper@1.1.1
15475 silly extract batch@0.6.1
15476 silly extract base64id@0.1.0
15477 silly extract base64-js@1.2.1
15478 silly extract base64-arraybuffer@0.1.2
15479 silly extract Base64@0.2.1
15480 verbose unlock done using /Users/michalczukm/.npm/_locks/staging-e2f2e3055f2a5219.lock for /Users/michalczukm/workspaces/github/mydatepicker/node_modules/.staging
15481 verbose type system
15482 verbose stack FetchError: request to https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz failed, reason: read ETIMEDOUT
15482 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
15482 verbose stack     at emitOne (events.js:115:13)
15482 verbose stack     at ClientRequest.emit (events.js:210:7)
15482 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:400:9)
15482 verbose stack     at emitOne (events.js:115:13)
15482 verbose stack     at TLSSocket.emit (events.js:210:7)
15482 verbose stack     at emitErrorNT (internal/streams/destroy.js:62:8)
15482 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
15482 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
15483 verbose cwd /Users/michalczukm/workspaces/github/mydatepicker
15484 verbose Darwin 17.0.0
15485 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-optional"
15486 verbose node v8.1.2
15487 verbose npm  v5.4.1
15488 error code ETIMEDOUT
15489 error errno ETIMEDOUT
15490 error network request to https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz failed, reason: read ETIMEDOUT
15491 error network This is a problem related to network connectivity.
15491 error network In most cases you are behind a proxy or have bad network settings.
15491 error network
15491 error network If you are behind a proxy, please make sure that the
15491 error network 'proxy' config is set properly.  See: 'npm help config'
15492 verbose exit [ 1, true ]
```

**Comment by pnrdk** [comment]
Is this options implemented?
