### ISSUE TITLE
Problem with universal

### ISSUE THREAD

**Issue by alyeldegwy** [kekeh/mydatepicker#420]
> XXX-web-client@0.0.0 prestart /home/XXX/Projects/XXX/XXX-web-client
> ng build --prod && ngc

 10% building modules 3/6 modules 3 active ...i/XXX-web-client/src/polyfills.tsThe final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
Hash: 9e0cacb7098d9f4537a2                                                              
Time: 76432ms
chunk    {0} main.6428429d1173dae767c0.bundle.js (main) 1.31 MB {3} [initial] [rendered]
chunk    {1} polyfills.b875f2c907a7cf03eea5.bundle.js (polyfills) 178 kB {4} [initial] [rendered]
chunk    {2} styles.8d7904042d27bdfc75e6.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.24f72377cf688f1e2da8.bundle.js (vendor) 2.2 MB [initial] [rendered]
chunk    {4} inline.1a8300b4990f06039972.bundle.js (inline) 0 bytes [entry] [rendered]

> XXX-web-client@0.0.0 start /home/XXX/Projects/XXX/XXX-web-client
> ts-node src/server.ts

/home/XXX/Projects/XXX/XXX-web-client/dist/ngfactory/node_modules/mydatepicker/dist/my-date-picker.component.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/XXX/Projects/XXX/XXX-web-client/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 4.10.0-041000-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! XXX-web-client@0.0.0 start: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the XXX-web-client@0.0.0 start script 'ts-node src/server.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the XXX-web-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node src/server.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs XXX-web-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls XXX-web-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/XXX/Projects/XXX/XXX-web-client/npm-debug.log

What To Do??

**Comment by kvincent3** [comment]
Hi @alyeldegwy,
Do you find a solution ?
