### ISSUE TITLE
Unittest failing with mydatepicker

### ISSUE THREAD

**Issue by ramden** [kekeh/mydatepicker#480]
Hello,
The Environment: 
Angular 5.0.3
Jest 21.2.1

Html:
`
  <my-date-picker name="birthday"
  editableDateField="false"
  placeholder="Select the patients date of birth"
  [options]="myDatePickerOptions"
  [locale]="getCurrentUserLocale()"
  [(ngModel)]="dateModel"
  required></my-date-picker>
`

In the unit test in beforeEach I do 
`
component = fixture.componentInstance;
fixture.detectChanges();
`

Error in **should create:**
**Error: TypeError: Cannot read property 'toString' of null**
      
      at viewWrappedDebugError (node_modules/@angular/core/bundles/core.umd.js:9543:15)
      at callWithDebugContext (node_modules/@angular/core/bundles/core.umd.js:14789:15)
      at Object.debugCheckAndUpdateView [as checkAndUpdateView] (node_modules/@angular/core/bundles/core.umd.js:14316:12)
      at ViewRef_.Object.<anonymous>.ViewRef_.detectChanges (node_modules/@angular/core/bundles/core.umd.js:11339:18)
      at ComponentFixture.Object.<anonymous>.ComponentFixture._tick (node_modules/@angular/core/bundles/core-testing.umd.js:220:32)`

If I comment out the html part test is passing.

**Comment by kekeh** [comment]
Can you try to exclude node_modules from your tests? I have done it in my own tests: https://github.com/kekeh/mydatepicker/blob/master/config/webpack.test.js

**Comment by judithowens** [comment]
It specifically happens in Angular 5 onwards when you have a datepicker that initialises with no date selected - if I work out a way to stub it I'll add a further comment.

**Comment by judithowens** [comment]
Okay, I have a working stub - it's not ideal, but it's an acceptable workaround for unit testing until I can get my code up to a sufficiently high version of Angular to switch.

Declare this stub inside your main component describe function before initialising your testbed:

`// Stub component as my-date-picker can't initialise in test with no starting value
    @Component({
        selector: 'my-date-picker', template: '', providers: [{
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => DatePickerStubComponent),
            multi: true
        }] })
    class DatePickerStubComponent {
        constructor() { }
        writeValue(): void { }
        registerOnChange(): void { }
        registerOnTouched(): void { }
    }`

And for your TestBed declaration:

`TestBed.configureTestingModule({
            imports: [FormsModule, ReactiveFormsModule],
            declarations: [
                ParentComponent,
                DatePickerStubComponent
            ],
            providers: [providers],
            schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]
        }).compileComponents();`
