### ISSUE TITLE
run "gulp all" faild

### ISSUE THREAD

**Issue by ChenReuven** [kekeh/mydatepicker#51]
Hey, 

i get this exception when try to run "gulp all" in windows: (i change the my-date-picker at src folder)

18:27:13] 'tsc.compile.dist' errored after 84 ms
[18:27:13] Error: Command failed: C:\windows\system32\cmd.exe /s /c "./node_modules/typescript/bin/tsc -p ./tsconfig.dist.json"
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
[18:27:13] 'all' errored after 524 ms
[18:27:13] Error in plugin 'run-sequence(tsc.compile.dist)'
Message:
    Command failed: C:\windows\system32\cmd.exe /s /c "./node_modules/typescript/bin/tsc -p ./tsconfig.dist.json"
'.' is not recognized as an internal or external command,
operable program or batch file.

Details:
    killed: false
    code: 1
    signal: null
    cmd: C:\windows\system32\cmd.exe /s /c "./node_modules/typescript/bin/tsc -p ./tsconfig.dist.json"
Stack:
Error: Command failed: C:\windows\system32\cmd.exe /s /c "./node_modules/typescript/bin/tsc -p ./tsconfig.dist.json"
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

Thanks :)

**Comment by kekeh** [comment]
Now take pull from the mydatepicker repository. Then run **npm install**. It installs the **gulp-typescript** package.

Then gulp all should work also in windows if you run command for example git bash.

**Comment by ChenReuven** [comment]
Thanks 4 your quick response
