### ISSUE TITLE
error on AOT compilation

### ISSUE THREAD

**Issue by designedev** [kekeh/mydatepicker#84]
found error on AOT compilation. (version 1.0.11)
----------------- error log -----------------
Error: Error at /projectDir/tmp/build/node_modules/mydatepicker/src/my-date-picker/directives/my-date-picker.input.directive.ngfactory.ts:23:20: **Property 'inputFocus' does not exist on type 'InputFocusDirective'.**
    at check (/projectDir/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/projectDir/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /projectDir/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
Compilation failed

how can i fix it ?

**Comment by kekeh** [comment]
I have already fixed AOT mode compilation here: https://github.com/kekeh/mydatepicker/issues/66

Latest **mydatepicker version is: 1.0.11**. Check AOT mode compilation result below.

```javascript
$ ng build -aot
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.                      6573ms building modules                                                                                              4ms add01386ms c58ms asset18ms emitting
Hash: 5cff3214d145f0b98aa6
Version: webpack 2.1.0-beta.25
Time: 8933ms
           Asset       Size  Chunks             Chunk Names
           0.map    2.85 kB          [emitted]  
  main.bundle.js    1.58 MB    0, 2  [emitted]  main
styles.bundle.js    10.2 kB    1, 2  [emitted]  styles
       inline.js    5.53 kB       2  [emitted]  inline
        main.map    1.62 MB    0, 2  [emitted]  main
      styles.map    14.1 kB    1, 2  [emitted]  styles
      inline.map    5.59 kB       2  [emitted]  inline
      index.html  477 bytes          [emitted]  
     favicon.ico    5.43 kB          [emitted]  
chunk    {0} main.bundle.js, main.map (main) 1.29 MB {1} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.map (styles) 9.96 kB {2} [initial] [rendered]
chunk    {2} inline.js, inline.map (inline) 0 bytes [entry] [rendered]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0       
    chunk    {0} index.html 344 bytes [entry] [rendered]
Child src/app/app.component.html:
                                                             Asset     Size  Chunks       Chunk Names
    /home/code/clitest/datepicker/src/app/app.component.html  2.54 kB       0       
    chunk    {0} /home/code/clitest/datepicker/src/app/app.component.html 104 bytes [entry] [rendered]
Child src/app/app.component.css:
                                                            Asset     Size  Chunks             Chunk Names
    /home/code/clitest/datepicker/src/app/app.component.css  2.61 kB       0             
                                                            0.map  2.85 kB       0  [emitted]  
    chunk    {0} /home/code/clitest/datepicker/src/app/app.component.css, 0.map 19 bytes [entry] [rendered]
$ 
```

**Comment by kekeh** [comment]
@designedev 

How you fixed this issue?
