### ISSUE TITLE
Error on AoT compilation

### ISSUE THREAD

**Issue by duki994** [kekeh/mydatepicker#93]
I get this error whenever i try to build app with AoT.
It works good without AoT

Unexpected value 'MyDatePickerModule' imported by the module 'AppModule'

```
Unexpected value 'MyDatePickerModule' imported by the module 'AppModule'
Error: Unexpected value 'MyDatePickerModule' imported by the module 'AppModule'
    at /home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:14675:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (/home/duki994/Documents/BEST/cv_app/node_modules/@angular/compiler/bundles/compiler.umd.js:12775:20)
    at CodeGenerator.codegen (/Users/chuckj/src/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at AotPlugin._make (/home/duki994/Documents/BEST/cv_app/node_modules/@ngtools/webpack/src/plugin.js:193:43)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/@ngtools/webpack/src/plugin.js:157:75)
    at Compiler.applyPluginsParallel (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/home/duki994/Documents/BEST/cv_app/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/home/duki994/Documents/BEST/cv_app/node_modules/webpack/lib/Compiler.js:210:7)
    at /home/duki994/Documents/BEST/cv_app/node_modules/angular-cli/tasks/build-webpack.js:24:29
    at Class.run (/home/duki994/Documents/BEST/cv_app/node_modules/angular-cli/tasks/build-webpack.js:23:16)
    at Class.run (/home/duki994/Documents/BEST/cv_app/node_modules/angular-cli/commands/build.js:51:26)
    at Class.<anonymous> (/home/duki994/Documents/BEST/cv_app/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Here's my module imports:
```
  imports: [
    MyDatePickerModule,
    BrowserModule,
    HttpModule,
    MaterialModule.forRoot(),
    routing,
    ReactiveFormsModule,
      FormsModule
  ],
```

Maybe some problem with decorators during transpilation?
I'm using Angular CLI.

**Comment by kekeh** [comment]
In my test **ng build -aot** works ok. I am using version **1.0.0-beta.19-3** of Angular CLI, version **2.1.0** of Angular and version **1.0.17** of mydatepicker.

app.module.ts:
```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { MyDatePickerModule } from 'mydatepicker';
import { SampleDatePickerNormal } from './sample-date-picker-normal/sample-date-picker-normal';

@NgModule({
  declarations: [
    AppComponent, SampleDatePickerNormal
  ],
  imports: [
    BrowserModule, FormsModule, HttpModule, MyDatePickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I don't have any idea what could be the reason.

**Comment by designedev** [comment]
in that case, i recomment copy ts files in /src to other directory and compile that files on AOT compilation.

i resolved same error using this solution.

**Comment by duki994** [comment]
I fixed this by updating Angular CLI and rearranging imports in module imports.
Thanks for idea @designdev

Compiler had problem with decorators. I don't know why but it seems to be common issue resolved by rearranging code.
