### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by sante85** [kekeh/mydatepicker#94]
app.module.ts 
import { MyDatePickerModule } from 'mydatepicker';
......
MyDatePickerModule in imports[]

I have this error while app load
app.js
export * from './src/my-date-picker/my-date-picker.module';

**Comment by kekeh** [comment]
What kind of configuration you have?

**Comment by harshabonthu** [comment]
@sante85 Not sure if this is the same error , I was getting undefined content import,etc pointed to `export * from './src/my-date-picker/my-date-picker.module';`. 

I'm using webpack and fix for that was adding `"main": "dist/index.js"` to package.json -> https://github.com/harshabonthu/mydatepicker/blob/master/package.json#L5

**Comment by kekeh** [comment]
Does it work without **main** property if you import **MyDatePickerModule** like below in your @NgModule:

import { MyDatePickerModule } from 'mydatepicker/src/my-date-picker/my-date-picker.module';

**Comment by harshabonthu** [comment]
Changing the import didn't work for me. Just tried below steps

Change import statement in my app.module.ts as `import { MyDatePickerModule } from 'mydatepicker/src/my-date-picker/my-date-picker.module';
`
Gives below error
```my-date-picker.module.ts:1 Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.typescriptSourcemapLoaderMemory (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/@ionic/app-scripts/dist/webpack/typescript-sourcemap-loader-memory.js:21:34)
    at Object.typescriptSourcemapLoaderMemory (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/@ionic/app-scripts/dist/webpack/typescript-sourcemap-loader-memory.js:21:34)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/mydatepicker/src/my-date-picker/my-date-picker.module.ts:1:7)
    at Object.<anonymous> (http://localhost:8100/build/main.js:12170:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/src/app/app.module.ts:33:113)
    at Object.<anonymous> (http://localhost:8100/build/main.js:8186:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/src/app/main.dev.ts:2:70)
    at Object.<anonymous> (http://localhost:8100/build/main.js:12164:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:64:18
```

Without the import statement change I get below error

```
/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/mydatepicker/index.ts:1 Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.typescriptSourcemapLoaderMemory (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/@ionic/app-scripts/dist/webpack/typescript-sourcemap-loader-memory.js:21:34)
    at Object.typescriptSourcemapLoaderMemory (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/@ionic/app-scripts/dist/webpack/typescript-sourcemap-loader-memory.js:21:34)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/node_modules/mydatepicker/index.ts:1:7)
    at Object.<anonymous> (http://localhost:8100/build/main.js:8853:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/src/app/app.module.ts:33:72)
    at Object.<anonymous> (http://localhost:8100/build/main.js:8182:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (/Users/harshabonthu/dev/demo.com/demoMobile/src/app/main.dev.ts:2:70)
    at Object.<anonymous> (http://localhost:8100/build/main.js:12163:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:64:18
```

With change in the import statement and adding `  "main": "dist/index.js",
` in  `node_modules/mydatepicker/package.json` breaks the app.

**Comment by kekeh** [comment]
I have already added main property to the package.json. I am closing this issue.
